### ISSUE TITLE
npm run dev failing

### ISSUE THREAD

**Issue by candidia** [YuraDev/vue-chrome-extension-template#19]
Console error
```
> vue-chrome-extension-template@0.0.1 dev /Users/f/Desktop/app/app
> webpack --config ./core/webpack.dev.js --hide-modules

/Users/f/Desktop/app/app/core/webpack.base.js:50
            ...cssLoaders(),
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/f/Desktop/app/app/core/webpack.dev.js:4:21)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-chrome-extension-template@0.0.1 dev script 'webpack --config ./core/webpack.dev.js --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-chrome-extension-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config ./core/webpack.dev.js --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-chrome-extension-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-chrome-extension-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/f/Desktop/app/app/npm-debug.log
```
Log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-chrome-extension-template@0.0.1~predev: vue-chrome-extension-template@0.0.1
6 silly lifecycle vue-chrome-extension-template@0.0.1~predev: no script for predev, continuing
7 info lifecycle vue-chrome-extension-template@0.0.1~dev: vue-chrome-extension-template@0.0.1
8 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/f/Desktop/app/app/node_modules/.bin:/Applications/Julia-0.6.app/Contents/Resources/julia/bin/:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Wireshark.app/Contents/MacOS
10 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: CWD: /Users/f/Desktop/app/app
11 silly lifecycle vue-chrome-extension-template@0.0.1~dev: Args: [ '-c',
11 silly lifecycle   'webpack --config ./core/webpack.dev.js --hide-modules' ]
12 silly lifecycle vue-chrome-extension-template@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle vue-chrome-extension-template@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-chrome-extension-template@0.0.1
16 verbose cwd /Users/f/Desktop/app/app
17 error Darwin 16.7.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
22 error Exit status 1
23 error Failed at the vue-chrome-extension-template@0.0.1 dev script 'webpack --config ./core/webpack.dev.js --hide-modules'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-chrome-extension-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config ./core/webpack.dev.js --hide-modules
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-chrome-extension-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-chrome-extension-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ngalluzzo** [comment]
Update your node version to 8+

**Comment by jasondu** [comment]
node v10.13.0, Still not working

**Comment by shouhuori** [comment]
> node v10.13.0, Still not working

Use node 8.x ,is work.
