### ISSUE TITLE
Webpack fails when testing extension

### ISSUE THREAD

**Issue by OctaneInteractive** [YuraDev/vue-chrome-extension-template#26]
Hi, I'm running this on Mac OS X 10.13.6 with Node v10.10.0.

Using the base installation of the template, I ran `npm run dev` and got a warning:

> { parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.

After that, making hot changes worked.

However, when:
1. I loaded the extension as unpacked at: "project/build";
2. clicked the button in the web browser;
3. and then clicked the "New tab" button, I got:

> internal/streams/legacy.js:57
>       throw er; // Unhandled stream error in pipe.
>       ^
> 
> Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue-chrome-extension-template@0.0.1 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/macbookpro/.npm/_logs/2019-04-19T10_05_16_155Z-debug.log

Where the _debug_ is:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/10.10.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'dev' ]
> 2 info using npm@6.4.1
> 3 info using node@v10.10.0
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle vue-chrome-extension-template@0.0.1~predev: vue-chrome-extension-template@0.0.1
> 6 info lifecycle vue-chrome-extension-template@0.0.1~dev: vue-chrome-extension-template@0.0.1
> 7 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: unsafe-perm in lifecycle true
> 8 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/path_to_server/project/node_modules/.bin:/Users/macbookpro/bin:/usr/local/bin:/usr/local/mysql/bin:/Users/macbookpro/.composer/vendor/bin:/usr/local/ec2/ec2-api-tools-1.7.5.1/bin:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
> 9 verbose lifecycle vue-chrome-extension-template@0.0.1~dev: CWD: /path_to_server/project
> 10 silly lifecycle vue-chrome-extension-template@0.0.1~dev: Args: [ '-c',
> 10 silly lifecycle   'webpack --config ./core/webpack.dev.js --hide-modules' ]
> 11 silly lifecycle vue-chrome-extension-template@0.0.1~dev: Returned: code: 1  signal: null
> 12 info lifecycle vue-chrome-extension-template@0.0.1~dev: Failed to exec dev script
> 13 verbose stack Error: vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:182:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:182:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:962:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 14 verbose pkgid vue-chrome-extension-template@0.0.1
> 15 verbose cwd /path_to_server/project
> 16 verbose Darwin 17.7.0
> 17 verbose argv "/usr/local/Cellar/node/10.10.0/bin/node" "/usr/local/bin/npm" "run" "dev"
> 18 verbose node v10.10.0
> 19 verbose npm  v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error vue-chrome-extension-template@0.0.1 dev: `webpack --config ./core/webpack.dev.js --hide-modules`
> 22 error Exit status 1
> 23 error Failed at the vue-chrome-extension-template@0.0.1 dev script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

I'm able to start Webpack up again, but it dies during testing, which is a shame.

**Comment by OctaneInteractive** [comment]
I opened the DevTools in Chrome and found a lot of errors.
![Screen Shot 2019-04-19 at 13 08 43](https://user-images.githubusercontent.com/419501/56423518-5b740700-62a4-11e9-9a49-b1414fc4890f.png)

**Comment by elkelk** [comment]
I got this working dropping by back to node v8.16.0

**Comment by OctaneInteractive** [comment]
Interesting, but a downgrade wouldn't be viable for me.
